docs: Cut dead features from recommended test/lint commands
Running the test command recommended in CONTRIBUTING.md gave:

    $ cargo test --features "wrap_help yaml regex unstable-replace"
    error: none of the selected packages contains these features: regex, yaml

Those two features were removed from Cargo.toml in #3963.
Remove them here too.